server:
  port: 80

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.company.project.seed.model
  configuration:
    map-underscore-to-camel-case: true
    use-column-label: true

mapper:
  mappers: tk.mybatis.mapper.common.Mapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  page-size-zero: true

spring:
  datasource:
    url: jdbc:mysql://db:3306/smartstore?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

logging:
  file: seed
